### ISSUE TITLE
update pwa.yaml to reflect 1.1.x changes

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa-demo#15]
The pwa.yaml file should be updated to reflect the changes in 1.1.x:

* regex->match_callback
* urls->preload_urls
* page_caches -> resource_caches
* strategies now begin with a capital letter

Something like this:

```yaml
        workbox:
            # https://pwa.spomky-labs.com/the-service-worker/workbox/warm-caching-1
            resource_caches:
                  - cache_name: page_cache
                    match_callback: 'regex: |/$|'
                    strategy: 'StaleWhileRevalidate'
                    broadcast: true
                    broadcast_headers:
                        - 'X-App-Cache'
                    preload_urls:
                    - 'app_homepage'
                  - cache_name: pages
                    match_callback: 'regex: |/api/.*$|'
#                    regex: "/api"
                    strategy: CacheFirst
                    broadcast: true
                    broadcast_headers:
                        - 'X-App-Cache'
            offline_fallback:
                page: 'app_homepage'
            background_sync:
                - queue_name: 'items'
                  match_callback: 'regex: {/items/.*$}'
                  broadcast_channel: 'items-sync'
                - queue_name: 'add'
                  match_callback: 'regex: |/add|'
                  method: POST
                  broadcast_channel: 'add-item'
```

I used pipes and brackets in the regex as I find it easier to read than

```yaml
'regex: \/articles\/.*$'
'regex: {/articles/.*$}'
```
