### ISSUE TITLE
/api route not caching

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa-demo#8]
I want to do a NetworkFirst then Cache strategy with this page:

https://phpwa-demo.survos.com/api/items.jsonld?page=1

My configuration is

```yaml
    serviceworker:
        enabled: true
        src: "sw.js"
        skip_waiting: true
        workbox:
            warm_cache_urls:
                - 'app_homepage'
                - '_api_/items{._format}_get_collection'
            page_fallback: 'app_homepage'
```
But that route doesn't show up anywhere in the service worker:

https://phpwa-demo.wip/sw.js
